### ISSUE TITLE
Add cage() method and live variable

### ISSUE THREAD

**Issue by alexisgayte** [BellwoodStudios/dss-psm#10]
We would like to be able to stop auction just in case ... .

Using the same design we can use live and cage()
with a require(live == 1) at the method entrance

**Comment by alexisgayte** [comment]
reopening this one just in case you want to consider it.

**Comment by hexonaut** [comment]
I'm following Maker design on this one, and the regular flipper does not have the ability to cage: https://github.com/makerdao/dss/blob/master/src/flip.sol

Governance always has the ability to shut the flipper off by de-authing it as well.

**Comment by alexisgayte** [comment]
While I understand we don't want to stop actual liquidation as the price can change, here the price is fixed and that makes the whole difference from my point of view. 

>Governance always has the ability to shut the flipper off by de-authing it as well.

Good point, If the feature is here I am closing it.
