### ISSUE TITLE
to be on the safeside check join.gem() != 0 

### ISSUE THREAD

**Issue by alexisgayte** [BellwoodStudios/dss-psm#8]
I guess  it might need to be checked.

https://github.com/BellwoodStudios/dss-psm/blob/ac61d164f89467a8a74ca8f6a7390e83898e0b0a/src/psmflip.sol#L67

**Comment by alexisgayte** [comment]
you can reject this one ... check is half-done

**Comment by alexisgayte** [comment]
Actually, 
I am a bit confuse here, as you check if actually strange. Why don't use the gem from the PSM directly. and remove one param from the constructor.
https://github.com/BellwoodStudios/dss-psm/blob/ac61d164f89467a8a74ca8f6a7390e83898e0b0a/src/psmflip.sol#L56

I would remove this line and check if it is != 0

**Comment by hexonaut** [comment]
This will error if that is the case. No need to check for 0.
